apiVersion: v1
kind: Service
metadata:
  name: {{ include "flask-hello-gitlab.fullname" . }}
  labels:
    app: "{{ .Chart.Name }}"
    version: "{{ .Chart.Version }}"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
  selector:
    app: "{{ .Chart.Name }}"
